
import sys
from bitarray import bitarray
from hashlib import sha1
import random
from random import randrange
import pdb

class StableBloomFilter(object):
    """
    Class Methods for Probabilistic Duplicate Detection
    """
    
    def __init__(self,max_val,no_bits,d,k,P):
        """
        max -- Max Value of each element in a Cell
        no_bits -- Number of bits to be generated by a Hash Function !
        d -- No of bits in each element in a Cell
        """
        m = 2**no_bits
        self.max=max_val
        self.d =d
        self.P = P #No of random cells to be chosen !
        self.total_size = m*d
        self.no_bits = no_bits
        self.no_hashes = k
        self.bitmap = bitarray(self.total_size)
        self.bitmap.setall(0)

    def _generate_parameters(self,fp_rate):
        """
        Generate Parameters given a FP Rate !!
        """
    def _gen_int_from_string(self,bin_string):
        """
        Generate integer value from Binary String 
        """
        int_val=0
        cnt=0
        for each in bin_string:            
            if each =='1':
                int_val+=int(each) * 2**cnt
            cnt+=1
        return int_val
            
    def _check_cell(self,cell_no):
        """
        Check if all bits in a Cell are 0
        """
        return self.bitmap[cell_no:cell_no+self.d].any()

    def _decrement_cell(self,cell_no,d,val=1):
        """
        Decrement Cell by 'val'
        Recommended Default is '1'
        """
        cell_value = self.bitmap[cell_no:cell_no+d].to01()
        int_val = self._gen_int_from_string(cell_value)
        if int_val>0:
            int_val-=1
            bin_val = bin(int_val)[2:]
            if len(bin_val)<=self.d:
                bin_val = '0'*(self.d-len(bin_val)) + bin_val            
            self.bitmap[cell_no:cell_no+d] = bitarray(bin_val)
        return True        
        
    def _update_cell(self,cell_no,d):
        """
        Updates the Cell of a Stable bloom Filter. Note that a Cell contains of 'd' elements
        """
        self.bitmap[cell_no:cell_no+d] = True

    def _choose_random_cells(self,P):
        """
        Returns Bucket Numbers of 'P' Random Celllls !!
        """
        generated_cells = {}        
        no_cells =0
        cell_list=[]
        while no_cells<P:
            rand_cell = randrange(0,self.total_size-1)
            if not generated_cells.get(rand_cell):
                no_cells+=1
                generated_cells[rand_cell]=True
                cell_list.append(rand_cell)
        return cell_list

    def process_element(self,text):
        """
        Handle A New Element Coming from a Stream. The Following Steps are done
        1) Randomly choose 'P' Cells and decrement
        """
        hash_buckets =[]
        dup_flag = True
        # Generate hash family functions
        for each_seed in xrange(self.no_hashes):
            hash_val = self._gen_hash(each_seed,text)
            # Probe each Cell
            dup_flag = dup_flag and self._check_cell(hash_val)
            hash_buckets.append(hash_val)  

        # Choose 'P' Different Cells !
        rand_cells = self._choose_random_cells(self.P)

        # Decrement the Random Cells by 1!        
        for each_cell in rand_cells:
            self._decrement_cell(each_cell,self.d)

        # Set all the Hash Values to Max !!        
        for each_cell in hash_buckets:
            self._update_cell(each_cell,self.d)

        return dup_flag        

    def _gen_hash(self,seed_no,text):
        """
        Generate a 'n' bit Hash for a certain seed.
        """
        random.seed(seed_no)
        seed_bits = random.getrandbits(self.no_bits)
        hash_obj = sha1()
        hash_obj.update(text)
        hash_val = int(bin(int(hash_obj.hexdigest(),16))[2:self.no_bits+2],2)
        return hash_val ^ seed_bits
    
if __name__=="__main__":
    ob = StableBloomFilter(5,24,7,10,7)
    pdb.set_trace()
    val = ob.process_element("This is just a piece of Sample Text")
    print val
    val = ob.process_element("This is just a piece of Sample Text")
    print val    
    print "Hello"
    
    


        
        

            
        

        




